[[legate]]
arch = "x86_64"
cuda = "12.2"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4360a9c0aa0d50e0c18d8fb40622f8c994c380cb"
lazy = true
libc = "glibc"
os = "linux"

    [[legate.download]]
    sha256 = "f94b6771ebc4067f572b36d65d83a4d5796ea3eb39ed2390b212616604a913c6"
    url = "https://github.com/ejmeitz/legate_jll.jl/releases/download/legate-v25.5.0+0/legate.v25.5.0.x86_64-linux-gnu-cxx11-cuda+12.2.tar.gz"
