# Autogenerated wrapper script for legate_jll for x86_64-linux-gnu-cxx11-cuda+12.2
export liblegate

using HDF5_jll
using MPICH_jll
using NCCL_jll
using Zlib_jll
using CompilerSupportLibraries_jll
using CUDA_Driver_jll
using CUDA_Runtime_jll
JLLWrappers.@generate_wrapper_header("legate")
JLLWrappers.@declare_library_product(liblegate, "liblegate.so.25.05.00")
function __init__()
    JLLWrappers.@generate_init_header(HDF5_jll, MPICH_jll, NCCL_jll, Zlib_jll, CompilerSupportLibraries_jll, CUDA_Driver_jll, CUDA_Runtime_jll)
    JLLWrappers.@init_library_product(
        liblegate,
        "lib/liblegate.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
